### PR TITLE
Simplify setup, add failing test, code coverage

### PR DESCRIPTION
**Pull request by briancavalier**
Just thinking out loud here, and all of this is totally up for discussion.

Two of the biggest changes are:
1. switching to the name `index.js` to avoid the two `mv` commands.  I'm not a huge fan of that name, but I also don't mind it. In this case, it makes life a bit easier.  Thoughts?
2. making the test fail by default :smiling_imp:.  My thinking is that this forces someone to at least look at it, although, maybe it's too heavy handed?

### CODE REVIEW

**Comment by briancavalier** [comment]
Added code coverage with isparta.  I'd rather use nyc, but [it's coverage reports are broken](https://github.com/bcoe/nyc/issues/110).  Maybe [something like this](https://gist.github.com/novemberborn/e133e9edabbb380229ca) would work, or we can wait for a fix and then switch.

**Comment by TylorS** [comment]
I don't know anything about code coverage, so I think that if this works for now I'm all for it.

**Comment by briancavalier** [comment]
Yeah, agreed.  I say we just go with isparta and keep an eye on nyc.

Any thoughts on `index.js` and making the test fail by default?

cc @davidchase

**Comment by davidchase** [comment]
The `index.js` seems like good convention... as it does make life easier we use that in our current project...

I think we can use what works for test coverage... i think nyc was done initially because of ava... could be wrong

what is the idea for failing the test by default? is that for consumer to be a good citizen before submitting their packages?

**Comment by briancavalier** [comment]
> I think we can use what works for test coverage

:+1:

> is that for consumer to be a good citizen before submitting their packages?

Yeah, although now I think it's too heavy-handed :)  Since we'll have test coverage, that's probably enough.

**Comment by TylorS** [comment]
`index.js` seems okay. That's what I was going to do originally, but it seemed to be of convention to name the 'main' file the same as the package name. e.g. `@most/dom-event` -> `dom-event.js`

Regarding the tests, I think having them fail is okay, if someone really doesn't want to write tests they could delete them.

**Comment by briancavalier** [comment]
Ok, I tweaked a few things.  Let me know what you think.
1. Test passes by default now.  I say we just pick pass or fail and run with it.  I picked pass.
2. Test uses function exported from index.js
3. Removed reference to `@most/core`, since it doesn't exist (yet)

**Comment by TylorS** [comment]
I think it all looks good

**Comment by briancavalier** [comment]
Any other thoughts, @davidchase?  Good to merge?

**Comment by davidchase** [comment]
yeah i think its good to merge... if you guys dont mind when i have sometime i still would like to tackle the `ava` and co setup just to see what i can come up with and see if any of that is viable both for curiosity and potential use in the project

**Comment by TylorS** [comment]
I have no issues with at least trying to move to ava in the future. It's always worth trying potentially better things. :+1:

Merge and transfer to the mostjs org?

**Comment by briancavalier** [comment]
> i still would like to tackle the ava and co setup

Sure :+1:

> Merge and transfer to the mostjs org?

:ok_hand: go for it!

**Comment by TylorS** [comment]
Merged and transferred

**Comment by briancavalier** [comment]
:boom:

**Pull request merged**
